const options = [
  { value: "emp_name", label: "Name" },
  { value: "name", label: "Department" },
  { value: "mobile_no", label: "Mobile No" },
  { value: "email", label: "Email" },
  { value: "gender", label: "Gender" },
  { value: "head_engineer", label: "Head Engineer" },
  { value: "id", label: "ID" },
  { value: "previous_designation", label: "Previous Designation" },
  { value: "designation_name", label: "Current Designation" },
  { value: "project_name", label: "Project Name" },
  { value: "current_salary", label: "Salary" },
  { value: "director", label: "Director" },
  { value: "remarks", label: "Remarks" },
  { value: "retired", label: "Retired" },
  { value: "wef", label: "WEF Date" },
  { value: "date_of_joining", label: "Date of Joining" },
  { value: "deduction", label: "Deduction %" },
  { value: "qualification", label: "Qualification" },
  { value: "previous_experience", label: "Previous Experience" },
  { value: "year_of_course_completion", label: "Year of Course Completion" },
  { value: "Basic_Salary", label: "Basic Salary" },
];
export default options;
